/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FinderRouteImport } from './routes/finder'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PantryRouteImport } from './routes/pantry'
import { Route as ShoppingListRouteImport } from './routes/shopping-list'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as CalendarIndexRouteImport } from './routes/calendar/index'
import { Route as CalendarProposalsRouteImport } from './routes/calendar/proposals'
import { Route as DraftsIndexRouteImport } from './routes/drafts/index'
import { Route as DraftsIdRouteImport } from './routes/drafts/$id'
import { Route as DraftsImportRouteImport } from './routes/drafts/import'
import { Route as DraftsNewRouteImport } from './routes/drafts/new'
import { Route as RecipesNewRouteImport } from './routes/recipes/new'
import { Route as RecipesIdIndexRouteImport } from './routes/recipes/$id/index'
import { Route as RecipesIdEditRouteImport } from './routes/recipes/$id/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FinderRoute = FinderRouteImport.update({
  id: '/finder',
  path: '/finder',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PantryRoute = PantryRouteImport.update({
  id: '/pantry',
  path: '/pantry',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoppingListRoute = ShoppingListRouteImport.update({
  id: '/shopping-list',
  path: '/shopping-list',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarIndexRoute = CalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarProposalsRoute = CalendarProposalsRouteImport.update({
  id: '/calendar/proposals',
  path: '/calendar/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIndexRoute = DraftsIndexRouteImport.update({
  id: '/drafts/',
  path: '/drafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsIdRoute = DraftsIdRouteImport.update({
  id: '/drafts/$id',
  path: '/drafts/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsImportRoute = DraftsImportRouteImport.update({
  id: '/drafts/import',
  path: '/drafts/import',
  getParentRoute: () => rootRouteImport,
} as any)
const DraftsNewRoute = DraftsNewRouteImport.update({
  id: '/drafts/new',
  path: '/drafts/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesNewRoute = RecipesNewRouteImport.update({
  id: '/recipes/new',
  path: '/recipes/new',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdIndexRoute = RecipesIdIndexRouteImport.update({
  id: '/recipes/$id/',
  path: '/recipes/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecipesIdEditRoute = RecipesIdEditRouteImport.update({
  id: '/recipes/$id/edit',
  path: '/recipes/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/api/$': typeof ApiSplatRoute
  '/calendar/proposals': typeof CalendarProposalsRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/drafts/import': typeof DraftsImportRoute
  '/drafts/new': typeof DraftsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/drafts/': typeof DraftsIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/api/$': typeof ApiSplatRoute
  '/calendar/proposals': typeof CalendarProposalsRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/drafts/import': typeof DraftsImportRoute
  '/drafts/new': typeof DraftsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/calendar': typeof CalendarIndexRoute
  '/drafts': typeof DraftsIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id': typeof RecipesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/finder': typeof FinderRoute
  '/library': typeof LibraryRoute
  '/login': typeof LoginRoute
  '/pantry': typeof PantryRoute
  '/shopping-list': typeof ShoppingListRoute
  '/api/$': typeof ApiSplatRoute
  '/calendar/proposals': typeof CalendarProposalsRoute
  '/drafts/$id': typeof DraftsIdRoute
  '/drafts/import': typeof DraftsImportRoute
  '/drafts/new': typeof DraftsNewRoute
  '/recipes/new': typeof RecipesNewRoute
  '/calendar/': typeof CalendarIndexRoute
  '/drafts/': typeof DraftsIndexRoute
  '/recipes/$id/edit': typeof RecipesIdEditRoute
  '/recipes/$id/': typeof RecipesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/finder'
    | '/library'
    | '/login'
    | '/pantry'
    | '/shopping-list'
    | '/api/$'
    | '/calendar/proposals'
    | '/drafts/$id'
    | '/drafts/import'
    | '/drafts/new'
    | '/recipes/new'
    | '/calendar/'
    | '/drafts/'
    | '/recipes/$id/edit'
    | '/recipes/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/finder'
    | '/library'
    | '/login'
    | '/pantry'
    | '/shopping-list'
    | '/api/$'
    | '/calendar/proposals'
    | '/drafts/$id'
    | '/drafts/import'
    | '/drafts/new'
    | '/recipes/new'
    | '/calendar'
    | '/drafts'
    | '/recipes/$id/edit'
    | '/recipes/$id'
  id:
    | '__root__'
    | '/'
    | '/finder'
    | '/library'
    | '/login'
    | '/pantry'
    | '/shopping-list'
    | '/api/$'
    | '/calendar/proposals'
    | '/drafts/$id'
    | '/drafts/import'
    | '/drafts/new'
    | '/recipes/new'
    | '/calendar/'
    | '/drafts/'
    | '/recipes/$id/edit'
    | '/recipes/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinderRoute: typeof FinderRoute
  LibraryRoute: typeof LibraryRoute
  LoginRoute: typeof LoginRoute
  PantryRoute: typeof PantryRoute
  ShoppingListRoute: typeof ShoppingListRoute
  ApiSplatRoute: typeof ApiSplatRoute
  CalendarProposalsRoute: typeof CalendarProposalsRoute
  DraftsIdRoute: typeof DraftsIdRoute
  DraftsImportRoute: typeof DraftsImportRoute
  DraftsNewRoute: typeof DraftsNewRoute
  RecipesNewRoute: typeof RecipesNewRoute
  CalendarIndexRoute: typeof CalendarIndexRoute
  DraftsIndexRoute: typeof DraftsIndexRoute
  RecipesIdEditRoute: typeof RecipesIdEditRoute
  RecipesIdIndexRoute: typeof RecipesIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finder': {
      id: '/finder'
      path: '/finder'
      fullPath: '/finder'
      preLoaderRoute: typeof FinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pantry': {
      id: '/pantry'
      path: '/pantry'
      fullPath: '/pantry'
      preLoaderRoute: typeof PantryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shopping-list': {
      id: '/shopping-list'
      path: '/shopping-list'
      fullPath: '/shopping-list'
      preLoaderRoute: typeof ShoppingListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/': {
      id: '/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof CalendarIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar/proposals': {
      id: '/calendar/proposals'
      path: '/calendar/proposals'
      fullPath: '/calendar/proposals'
      preLoaderRoute: typeof CalendarProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/': {
      id: '/drafts/'
      path: '/drafts'
      fullPath: '/drafts/'
      preLoaderRoute: typeof DraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/$id': {
      id: '/drafts/$id'
      path: '/drafts/$id'
      fullPath: '/drafts/$id'
      preLoaderRoute: typeof DraftsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/import': {
      id: '/drafts/import'
      path: '/drafts/import'
      fullPath: '/drafts/import'
      preLoaderRoute: typeof DraftsImportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/drafts/new': {
      id: '/drafts/new'
      path: '/drafts/new'
      fullPath: '/drafts/new'
      preLoaderRoute: typeof DraftsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/new': {
      id: '/recipes/new'
      path: '/recipes/new'
      fullPath: '/recipes/new'
      preLoaderRoute: typeof RecipesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/': {
      id: '/recipes/$id/'
      path: '/recipes/$id'
      fullPath: '/recipes/$id/'
      preLoaderRoute: typeof RecipesIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recipes/$id/edit': {
      id: '/recipes/$id/edit'
      path: '/recipes/$id/edit'
      fullPath: '/recipes/$id/edit'
      preLoaderRoute: typeof RecipesIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinderRoute: FinderRoute,
  LibraryRoute: LibraryRoute,
  LoginRoute: LoginRoute,
  PantryRoute: PantryRoute,
  ShoppingListRoute: ShoppingListRoute,
  ApiSplatRoute: ApiSplatRoute,
  CalendarProposalsRoute: CalendarProposalsRoute,
  DraftsIdRoute: DraftsIdRoute,
  DraftsImportRoute: DraftsImportRoute,
  DraftsNewRoute: DraftsNewRoute,
  RecipesNewRoute: RecipesNewRoute,
  CalendarIndexRoute: CalendarIndexRoute,
  DraftsIndexRoute: DraftsIndexRoute,
  RecipesIdEditRoute: RecipesIdEditRoute,
  RecipesIdIndexRoute: RecipesIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
